In [1]:
import numpy as np

In [4]:
ND = np.random.randint(0,10,(4,4)) # element- wise işlemler 
ND

array([[9, 8, 6, 1],
       [2, 1, 1, 4],
       [3, 3, 5, 9],
       [1, 1, 0, 3]])

In [5]:
ND +2

array([[11, 10,  8,  3],
       [ 4,  3,  3,  6],
       [ 5,  5,  7, 11],
       [ 3,  3,  2,  5]])

In [8]:
ND2 = np.random.randint(0,10,(4,4))
ND2

array([[3, 1, 1, 6],
       [0, 4, 0, 4],
       [2, 6, 6, 5],
       [0, 7, 0, 1]])

In [11]:
ND + ND2

array([[12,  9,  7,  7],
       [ 2,  5,  1,  8],
       [ 5,  9, 11, 14],
       [ 1,  8,  0,  4]])

In [16]:
ND3 = np.random.randint(0,10,(2,2))
ND4 = np.random.randint(0,10,(1,3))

In [17]:
ND3

array([[9, 3],
       [5, 4]])

In [18]:
ND4

array([[1, 8, 2]])

In [19]:
ND3 + ND4

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 