In [1]:
import numpy as np

In [3]:
ND = np.arange(15).reshape(3,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
ND[1,1]

6

In [5]:
ND[2,3]

13

In [6]:
ND[1]

array([5, 6, 7, 8, 9])

In [8]:
ND[:,2]

array([ 2,  7, 12])

In [9]:
ND = np.arange(15).reshape(3,5)
ND


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
ND[:,2]= 44
ND

array([[ 0,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14]])

In [11]:
# axis =0 satır axis =1 sütun 

In [12]:
ND = np.append(ND , [[7,7,7,7,7]], axis=0)
ND

array([[ 0,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14],
       [ 7,  7,  7,  7,  7]])

In [13]:
ND = np.insert(ND,0 , [[6,6,6,6,6]], axis=0)
ND

array([[ 6,  6,  6,  6,  6],
       [ 0,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14],
       [ 7,  7,  7,  7,  7]])

In [14]:
ND

array([[ 6,  6,  6,  6,  6],
       [ 0,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14],
       [ 7,  7,  7,  7,  7]])

In [16]:
ND = np.append(ND , [[99],[99],[99],[99],[99]], axis=1)
ND

array([[ 6,  6,  6,  6,  6, 99],
       [ 0,  1, 44,  3,  4, 99],
       [ 5,  6, 44,  8,  9, 99],
       [10, 11, 44, 13, 14, 99],
       [ 7,  7,  7,  7,  7, 99]])

In [ ]:
ND = np.insert(ND ,0, [[]], axis=0)
ND