In [6]:
import numpy as np 

In [7]:
ND =np.array([1,2,3,4,5])
ND

array([1, 2, 3, 4, 5])

In [10]:
ND=np.array([[1,2,3,4,5],[1,2,3,4,5]])
ND

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
ND.shape

(2, 5)

In [12]:
ND.ndim #ka. boyutlu 

2

In [13]:
ND.dtype  #veri tipini gösterir

dtype('int32')

In [14]:
ND.size # eleman sayısını veerir

10

In [15]:
ND3 = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
ND3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [16]:
ND3.ndim  # boyut sayısı

3

In [17]:
ND3.size #eleman sayısı

20

In [18]:
ND3.shape # 

(2, 2, 5)

In [19]:
ND0 = np.array(4)
ND0

array(4)

In [22]:
type(ND0)

numpy.ndarray

In [23]:
ND0.ndim

0

In [24]:
NDX = np.array([4])
NDX

array([4])

In [25]:
NDX.ndim

1