In [3]:
import numpy as np

In [2]:
benimdizim = np.arange(0,15)

In [3]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimdizim[5]

5

In [6]:
benimdizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimdizim[3:8]= -6

In [9]:
benimdizim

array([ 0,  1,  2, -6, -6, -6, -6, -6,  8,  9, 10, 11, 12, 13, 14])

In [11]:
baskadizi=  np.arange(0,24)

In [12]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingdizi = baskadizi[0:5]

In [15]:
slicingdizi

array([0, 1, 2, 3, 4])

In [16]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
slicingdizi[:] = 600

In [18]:
slicingdizi

array([600, 600, 600, 600, 600])

In [19]:
baskadizi

array([600, 600, 600, 600, 600,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
ornekdizi = np.arange(0,24)

In [21]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekdizikopyasi = ornekdizi.copy()

In [23]:
ornekdizikopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekdizislicing = ornekdizikopyasi[6:10]

In [25]:
ornekdizislicing[:] = 800

In [26]:
ornekdizislicing

array([800, 800, 800, 800])

In [27]:
ornekdizikopyasi

array([  0,   1,   2,   3,   4,   5, 800, 800, 800, 800,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix


In [1]:
benimlistem= [[10,20,30],[20,30,40],[40,50,60]]

In [5]:
benimmatrixdizim = np.array(benimlistem)

In [6]:
benimmatrixdizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [7]:
benimmatrixdizim[0]

array([10, 20, 30])

In [9]:
benimmatrixdizim[1][2]

40

In [10]:
benimmatrixdizim[1,2]

40

In [11]:
benimmatrixdizim[1:,2]

array([40, 60])

In [12]:
yeniliste =[ [0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [13]:
yenimatrix= np.array(yeniliste)

In [14]:
yenimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
yenimatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## oprasyonlar 

In [19]:
yenibirdizi = np.random.randint(1,100,20)

In [20]:
yenibirdizi

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 18, 88, 87, 64, 95, 13,
       58, 49, 23])

In [21]:
yenibirdizi > 24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [22]:
yenibirdizi

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 18, 88, 87, 64, 95, 13,
       58, 49, 23])

In [24]:
sonuc= yenibirdizi >24

In [25]:
sonuc


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [26]:
yenibirdizi

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 18, 88, 87, 64, 95, 13,
       58, 49, 23])

In [27]:
yenibirdizi[sonuc]

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 88, 87, 64, 95, 58, 49])

In [28]:
yenibirdizi

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 18, 88, 87, 64, 95, 13,
       58, 49, 23])

In [29]:
yenibirdizi[yenibirdizi > 24]

array([57, 42, 62, 53, 54, 97, 54, 37, 28, 29, 42, 88, 87, 64, 95, 58, 49])

In [31]:
sondizi = np.arange(0,24)

In [32]:
sondizi +sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [33]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
sondizi *sondizi


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [35]:
sondizi - sondizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [36]:
sondizi /sondizi

<ipython-input-36-3b93e1eec6f2>:1: RuntimeWarning: invalid value encountered in true_divide
  sondizi /sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [38]:
np.max(sondizi)

23