In [4]:
import numpy as np 

## numpy array 

In [5]:
benimlistem= [20,30,40,50]

In [6]:
np.array(benimlistem)

array([20, 30, 40, 50])

In [7]:
matrixlistesi= [[10,20,30],[20,30,40],[30,40,50]]

In [8]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

##arange

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [19]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## eye

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random 

In [21]:
np.random.randn(8)

array([ 0.84153857, -0.5782338 , -0.74530877, -0.53826562, -0.44021223,
       -0.17708481, -1.41177073, -2.02191604])

In [23]:
np.random.randn(4,8)

array([[ 0.60367292,  0.26674721,  0.31861216,  0.534819  , -1.91697874,
         0.60644986, -0.14696087, -0.25411604],
       [-1.48211842, -1.4929199 , -1.17081419, -1.72984806, -1.24481899,
        -2.41810383, -0.91984286, -0.46664792],
       [-2.13390615,  0.2915165 ,  1.12835388, -0.75417883, -0.02218132,
        -0.41656159, -0.78490415, -0.88143351],
       [ 1.61073403, -1.00019969, -1.28114624, -0.83000074,  1.58324497,
         0.68395115, -0.69391973,  0.0381462 ]])

In [27]:
np.random.randint(1,10)

9

In [30]:
np.random.randint(1,10,5)

array([7, 3, 3, 7, 1])

In [31]:
np.random.randint(1,300,5)

array([195,  38, 142, 226, 219])

In [32]:
benimnumpydizim= np.arange(30)

In [33]:
benimnumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
benimrandomdizim= np.random.randint(0,100,30)

In [35]:
benimrandomdizim

array([ 4, 95, 13, 36, 56, 50, 99,  4, 17, 48, 86, 74, 75, 16, 46, 58, 88,
       32, 80, 36, 50, 58, 10, 39, 54, 42,  3, 10, 58,  3])

## numpy dizi metodları 

In [37]:
benimnumpydizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
benimnumpydizim.max()

29

In [40]:
benimrandomdizim.max()

99

In [41]:
benimrandomdizim.min()

3

In [43]:
benimrandomdizim.argmax() # kaçıncı indexte olduğunu söyler

6

In [44]:
benimrandomdizim.argmin()

26

In [45]:
benimnumpydizim.shape

(30,)