In [1]:
import numpy as np

In [2]:
ND = np.arange(20).reshape(4,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
ND[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
ND[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
ND[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
ND[:2 ,:2]

array([[0, 1],
       [5, 6]])

In [11]:
ND[1:4, 2:4]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [13]:
ND = np.random.randint(0,10,(4,5))
ND

array([[1, 3, 6, 9, 5],
       [8, 5, 3, 5, 8],
       [4, 8, 3, 9, 0],
       [3, 2, 6, 6, 9]])

In [14]:
ND[:] >=5


array([[False, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True, False],
       [False, False,  True,  True,  True]])

In [16]:
ND[ND[:] >=5]

array([6, 9, 5, 8, 5, 5, 8, 8, 9, 6, 6, 9])

In [17]:
ND

array([[1, 3, 6, 9, 5],
       [8, 5, 3, 5, 8],
       [4, 8, 3, 9, 0],
       [3, 2, 6, 6, 9]])

In [18]:
(ND[:] >=5) & (ND[:] <8)

array([[False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False]])